# Generated by Django 5.0.2 on 2024-02-22 14:44

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("wechat_login", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="user",
            table="wechat_user",
        ),
    ]
