# Generated by Django 5.0.2 on 2024-02-22 14:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("UserRegister", "0001_initial"),
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="customuser",
            options={},
        ),
        migrations.AlterField(
            model_name="customuser",
            name="groups",
            field=models.ManyToManyField(
                blank=True,
                related_name="custom_user_groups",
                to="auth.group",
                verbose_name="groups",
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="user_permissions",
            field=models.ManyToManyField(
                blank=True,
                related_name="custom_user_user_permissions",
                to="auth.permission",
                verbose_name="user permissions",
            ),
        ),
        migrations.AlterModelTable(
            name="customuser",
            table="custom_user",
        ),
        migrations.AlterModelTable(
            name="userregister",
            table="user_register",
        ),
    ]
