# Generated by Django 5.0.2 on 2024-02-19 12:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("pets", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="adoption",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="adoptions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="accounting",
            name="donation",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="pets.donation"
            ),
        ),
        migrations.AddField(
            model_name="adoption",
            name="pet",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="adoptions",
                to="pets.pet",
            ),
        ),
        migrations.AddField(
            model_name="donation",
            name="project",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="pets.project"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="accounting",
            unique_together={("donation", "donation_date")},
        ),
        migrations.AlterUniqueTogether(
            name="adoption",
            unique_together={("pet", "user")},
        ),
    ]
