# Generated by Django 5.0.2 on 2024-02-20 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='region',
            field=models.CharField(choices=[('W', '文理学部'), ('G', '工学部'), ('X', '信息学部'), ('Y', '医学部')], default='Unknown', max_length=100),
        ),
    ]
