# Generated by Django 5.0.2 on 2024-02-22 13:36

import django.utils.timezone
from django.utils import timezone
from django.db import migrations, models
from pets.models import Adoption


def set_request_date(apps, schema_editor):
    Adoption.objects.all().update(request_date=timezone.now())


class Migration(migrations.Migration):
    dependencies = [
        ("pets", "0003_pet_region"),
    ]

    operations = [
        migrations.AddField(
            model_name="adoption",
            name="request_date",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.RunPython(set_request_date),
    ]
