# Generated by Django 5.0.2 on 2024-03-11 04:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pets", "0004_adoption_request_date"),
    ]

    operations = [
        migrations.RenameField(
            model_name="pet",
            old_name="health_status",
            new_name="health",
        ),
        migrations.RenameField(
            model_name="pet",
            old_name="avatar",
            new_name="image",
        ),
        migrations.RenameField(
            model_name="pet",
            old_name="region",
            new_name="position",
        ),
        migrations.RemoveField(
            model_name="pet",
            name="distribution",
        ),
        migrations.RemoveField(
            model_name="pet",
            name="is_adoptable",
        ),
        migrations.RemoveField(
            model_name="pet",
            name="weight",
        ),
        migrations.AddField(
            model_name="pet",
            name="feature",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="pet",
            name="gender",
            field=models.CharField(
                choices=[("M", "Male"), ("F", "Female")],
                default="Unknown",
                max_length=1,
            ),
        ),
        migrations.AddField(
            model_name="pet",
            name="other",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="pet",
            name="personality",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="pet",
            name="range",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="pet",
            name="sterilization",
            field=models.BooleanField(default=False),
        ),
    ]
