# Generated by Django 5.0.2 on 2024-03-20 07:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pets", "0005_rename_health_status_pet_health_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="pet",
            name="condition",
            field=models.CharField(
                choices=[("X", "在校"), ("L", "被领养"), ("M", "喵星")],
                default="Unknown",
                max_length=1,
            ),
        ),
        migrations.AddField(
            model_name="pet",
            name="social",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="pet",
            name="status",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
