# Generated by Django 5.0.2 on 2024-02-19 12:51

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AdoptionRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "request_date",
                    models.DateTimeField(auto_now_add=True, verbose_name="申请日期"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "正在审核"),
                            ("approved", "审核通过"),
                            ("rejected", "审核不通过"),
                        ],
                        default="pending",
                        max_length=10,
                        verbose_name="审核状态",
                    ),
                ),
            ],
            options={
                "verbose_name": "领养申请",
                "verbose_name_plural": "领养申请",
            },
        ),
    ]
